name: Building

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      -
        name: Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/arxprotocol/sapphire-rpc-proxy:${{ github.ref_name }}
          secrets: |
            "github_token=${{ secrets.GITHUB_TOKEN }}"
